typo that prevents install
\item instead of \iten, which causes an error upon install with {remotes}

```
remotes::install_github("Jean-Romain/lidR@devel")

...
Error : (converted from warning) /private/var/folders/xl/hy7rwmvx4llff5_00gwbk2vh0000gp/T/RtmpfKPFkY/R.INSTALLe5de7a1086de/lidR/man/LAScatalog-class.Rd:116: unknown macro '\iten'
ERROR: installing Rd objects failed for package ‘lidR’

...
```